"use client";

import { useState } from "react";
import { Sparkles, Lock, ArrowRight, Loader2 } from "lucide-react";
import toast from "react-hot-toast";

interface PremiumUnlockButtonProps {
  onUnlock: () => void;
  title?: string;
  description?: string;
  buttonText?: string;
  className?: string;
}

export default function PremiumUnlockButton({
  onUnlock,
  title = "Premium Feature",
  description = "Support UniGig by interacting with our sponsor to unlock this feature instantly!",
  buttonText = "Unlock Now",
  className = ""
}: PremiumUnlockButtonProps) {
  const [isUnlocking, setIsUnlocking] = useState(false);
  const [isHovered, setIsHovered] = useState(false);

  // The Smartlink generated by Adsterra
  const SMARTLINK_URL = "https://www.effectivecpmnetwork.com/ib1kztzzfp?key=bf5eabb5b1fdd3fb30bf20535189d771";

  const handleUnlock = () => {
    setIsUnlocking(true);
    
    // 1. Open the Adsterra Smartlink in a new tab
    const newWindow = window.open(SMARTLINK_URL, '_blank', 'noopener,noreferrer');
    
    if (newWindow) {
      toast.loading("Verifying interaction...", { id: "unlock-toast" });
      
      // We wait for the user to return to this tab to guarantee they actually viewed the ad tab
      let hasUnlocked = false;

      const completeUnlock = () => {
        if (hasUnlocked) return;
        hasUnlocked = true;
        
        setIsUnlocking(false);
        toast.success("Feature Unlocked!", { id: "unlock-toast" });
        onUnlock();
        
        // Clean up listeners
        window.removeEventListener('focus', completeUnlock);
        document.removeEventListener('visibilitychange', handleVisibility);
      };

      const handleVisibility = () => {
        if (document.visibilityState === 'visible') {
          completeUnlock();
        }
      };

      // Listen for when they switch back to our tab
      window.addEventListener('focus', completeUnlock);
      document.addEventListener('visibilitychange', handleVisibility);
      
      // Safety fallback in case the browser blocks focus events
      setTimeout(() => {
        completeUnlock();
      }, 5000);

    } else {
      // If the browser blocks the popup
      setIsUnlocking(false);
      toast.error("Please allow popups to unlock this feature.");
    }
  };

  return (
    <div className={`bg-gradient-to-br from-amber-50 to-orange-50 border border-amber-200/50 rounded-2xl p-5 shadow-sm relative overflow-hidden group ${className}`}>
      {/* Decorative background element */}
      <div className="absolute -right-4 -top-4 w-24 h-24 bg-gradient-to-br from-amber-400 to-orange-500 rounded-full opacity-10 group-hover:scale-150 transition-transform duration-700 blur-xl" />
      
      <div className="relative z-10">
        <div className="flex items-center gap-2.5 mb-2">
          <div className="bg-gradient-to-br from-amber-400 to-orange-500 p-1.5 rounded-lg shadow-sm">
            <Lock className="w-4 h-4 text-white" />
          </div>
          <h3 className="font-extrabold text-gray-900">{title}</h3>
        </div>
        
        <p className="text-sm text-gray-600 mb-4 leading-relaxed pr-4">
          {description}
        </p>
        
        <button
          onClick={handleUnlock}
          disabled={isUnlocking}
          onMouseEnter={() => setIsHovered(true)}
          onMouseLeave={() => setIsHovered(false)}
          className="w-full flex items-center justify-center gap-2 bg-black hover:bg-gray-900 text-white font-bold py-2.5 px-4 rounded-xl transition-all duration-200 active:scale-95 disabled:opacity-70 disabled:active:scale-100"
        >
          {isUnlocking ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <>
              <Sparkles className={`w-4 h-4 text-amber-400 ${isHovered ? 'animate-pulse' : ''}`} />
              {buttonText}
              <ArrowRight className={`w-4 h-4 transition-transform duration-300 ${isHovered ? 'translate-x-1' : ''}`} />
            </>
          )}
        </button>
      </div>
    </div>
  );
}
