"use client";

import { useState } from "react";
import { Sparkles, Lock, ArrowRight, Loader2 } from "lucide-react";
import toast from "react-hot-toast";

interface PremiumUnlockButtonProps {
  onUnlock: () => void;
  title?: string;
  description?: string;
  buttonText?: string;
  className?: string;
}

export default function PremiumUnlockButton({
  onUnlock,
  title = "Premium Feature",
  description = "Support GigTic by interacting with our sponsor to unlock this feature instantly!",
  buttonText = "Unlock Now",
  className = ""
}: PremiumUnlockButtonProps) {
  const [isUnlocking, setIsUnlocking] = useState(false);
  const [isHovered, setIsHovered] = useState(false);

  // The Smartlink generated by Adsterra (Anti-Adblock Encrypted)
  const SMARTLINK_URL = "https://www.effectivecpmnetwork.com/wa8nemaf?key=57fa9354e17d41554d4b666d8b564e3a";

  const handleUnlock = () => {
    setIsUnlocking(true);
    
    // Instantly unlock the feature when the link is clicked
    setTimeout(() => {
      setIsUnlocking(false);
      toast.success("Feature Unlocked!", { id: "unlock-toast" });
      onUnlock();
    }, 100);
  };

  return (
    <div className={`bg-gradient-to-br from-amber-50 to-orange-50 border border-amber-200/50 rounded-2xl p-5 shadow-sm relative overflow-hidden group ${className}`}>
      {/* Decorative background element */}
      <div className="absolute -right-4 -top-4 w-24 h-24 bg-gradient-to-br from-amber-400 to-orange-500 rounded-full opacity-10 group-hover:scale-150 transition-transform duration-700 blur-xl" />
      
      <div className="relative z-10">
        <div className="flex items-center gap-2.5 mb-2">
          <div className="bg-gradient-to-br from-amber-400 to-orange-500 p-1.5 rounded-lg shadow-sm">
            <Lock className="w-4 h-4 text-white" />
          </div>
          <h3 className="font-extrabold text-gray-900">{title}</h3>
        </div>
        
        <p className="text-sm text-gray-600 mb-4 leading-relaxed pr-4">
          {description}
        </p>
        
        <a
          href={SMARTLINK_URL}
          target="_blank"
          rel="noopener noreferrer"
          onClick={handleUnlock}
          onMouseEnter={() => setIsHovered(true)}
          onMouseLeave={() => setIsHovered(false)}
          className={`w-full flex items-center justify-center gap-2 bg-black hover:bg-gray-900 text-white font-extrabold py-2.5 px-4 rounded-2xl transition-all duration-200 active:scale-95 ${isUnlocking ? 'opacity-70 pointer-events-none' : ''}`}
        >
          {isUnlocking ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <>
              <Sparkles className={`w-4 h-4 text-amber-400 ${isHovered ? 'animate-pulse' : ''}`} />
              {buttonText}
              <ArrowRight className={`w-4 h-4 transition-transform duration-300 ${isHovered ? 'translate-x-1' : ''}`} />
            </>
          )}
        </a>
      </div>
    </div>
  );
}
